#
# Python Project Toml
#

# Bandit
[tool.bandit]
skips = ["B101"]

# Black
[tool.black]
line-length = 100

# Flake8
[tool.flake8]
max-line-length = 100
ignore = "E402, W503"

# Codespell
[tool.codespell]
count = ''
quiet-level = 3

# Coverage
[tool.coverage.paths]
source = ["src"]
tests = ["tests"]

[tool.coverage.run]
branch = true
sigterm = true
source = ["src"]

[tool.coverage.report]
exclude_also = [
    "def main()",
    "if __name__ == .__main__.:",
]
fail_under = 70
show_missing = true
skip_empty = true

[tool.coverage.html]
directory = "reports/htmlcov"

[tool.coverage.xml]
output = "reports/coverage-results.xml"

# Interrogate
[tool.interrogate]
fail-under = 70

# Docformatter
[tool.docformatter]
recursive = true
in-place = true
wrap-descriptions = 0
wrap-summaries = 0
blank = true

# Isort
[tool.isort]
known_first_party = "src"
lines_after_imports = 2
profile = "black"

# Mypy
[tool.mypy]
files = "src"
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
strict = true
warn_unreachable = true
ignore_missing_imports = true

# Pylint
[tool.pylint.main]
disable = ["no-else-return"]
fail-under = 7
jobs = 0
load-plugins = ["pylint.extensions.mccabe"]
max-complexity = 25

[tool.pylint.format]
good-names = [
    'i',
    'j',
    'k',
    'ex',
    'Run',
    '_',
]
max-line-length = 100
max-args = 10
max-locals = 25

[tool.pylint.reports]
output-format = "colorized"

[tool.pylint.messages_control]
disable = ["E0401"]

# Pytest
[tool.pytest.ini_options]
addopts = "--color=yes --strict-markers --junit-xml=reports/xunit-results.xml"
testpaths = ["tests"]
