name: CI Pipeline

on:
  pull_request:
    branches:
      - main
    tags-ignore:
      - 'v*'  # Ignoring release tags

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      # Add any environment variables here

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9  # Specify the Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming a generic requirements file
          pip install -e .

      - name: Run Unit Tests
        run: |
          echo "Running unit tests..."
          pytest tests/unit

      - name: Deploy Integration Test [Staging]
        if: ${{ github.ref == 'refs/heads/main' }}  # Conditional deployment
        run: |
          echo "Deploying integration test to staging..."

      - name: Run Integration Test [Staging]
        if: ${{ github.ref == 'refs/heads/main' }}  # Conditional test run
        run: |
          echo "Running integration test in staging environment..."
