pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Linter
    jobs:
      - job: TestJob
        steps:
          - checkout: self
          - script: echo "Hello, World!"
            displayName: "Run a simple script"
