# Triggers
trigger:
  # All Commits
  branches:
    include:
      - '*'
  # All Tags
  tags:
    include:
      - '*'
# All Pull Requests
pr:
  branches:
    include:
      - '*'
# Pool configuration: define the VM image to use
pool:
  vmImage: 'ubuntu-latest'

# Link variable groups
variables:
  - group: AWSVariables
  - group: DockerCredentials

# Define stages
stages:
  # Build and Push Docker Image to Staging
  - stage: Staging
    displayName: "Deploy to Staging"
    jobs:
      - job: docker_build_and_push_staging
        displayName: "Build Docker Image and Push to Docker Hub (Staging)"
        steps:
          - checkout: self

          # Debugging to see the value of DOCKER_USERNAME
          - script: echo "DOCKER_USERNAME is- $(DOCKER_USERNAME)"
            displayName: "Print DOCKER_USERNAME"

          # Build Docker image for staging
          - task: Docker@2
            displayName: 'Build Docker Image for Staging'
            inputs:
              containerRegistry: 'docker-hub-connection'  # Use your service connection name here
              repository: '$(DOCKER_USERNAME)/mlops-aws-windoutput-staging'  # Staging repository
              command: 'buildAndPush'
              Dockerfile: 'Dockerfile'  # Path to your Dockerfile
              tags: 'staging-latest'

  # Build and Push Docker Image to Production on Tag Creation
  - stage: Production
    displayName: "Deploy to Production"
    dependsOn: Staging
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/v'))
    jobs:
      - job: docker_build_and_push_prod
        displayName: "Build Docker Image and Push to Docker Hub (Production)"
        steps:
          - checkout: self

          # Debugging to see the value of DOCKER_USERNAME
          - script: echo "DOCKER_USERNAME is- $(DOCKER_USERNAME)"
            displayName: "Print DOCKER_USERNAME"

          # Build Docker image for production
          - task: Docker@2
            displayName: 'Build Docker Image for Production'
            inputs:
              containerRegistry: 'docker-hub-connection'  # Use your service connection name here
              repository: '$(DOCKER_USERNAME)/mlops-aws-windoutput'  # Production repository
              command: 'buildAndPush'
              Dockerfile: 'Dockerfile'  # Path to your Dockerfile
              tags: |
                latest
                $(Build.BuildId)
