# Azure DevOps pipeline with MaxConcurrency set to 1

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test Job'
  concurrency:
    cancelInProgress: false  # Set to true to cancel running jobs when a new one is triggered
    maxConcurrent: 1          # Set max concurrency to 1

  steps:
    - checkout: self
      displayName: 'Checkout source code'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
      displayName: 'Set up Python'

    - script: |
        pip install tox==4.20.0
      displayName: 'Install tox version 4.20.0'

    - script: |
        tox
      displayName: 'Run tests with tox'
