# Pull request validation
pr:
  branches:
    include:
      - main               # Validate PRs targeting the main branch

# Pool configuration: define the VM image to use
pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu image for running the pipeline

# Define stages
stages:
  # Linter stage
  - stage: Linter            # Name of the stage
    displayName: "Run Code Linters"
    dependsOn: []            # No dependencies for this stage
    jobs:
      # Job to run Pylint
      - job: tox_linting      # Name of the job
        displayName: "Running Tox Linting"
        steps:
          # Checkout code
          - checkout: self   # Checkout the current repository code

          # Set up Python environment
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'     # Specify Python version
              addToPath: true

          # Install dependencies and run Tox with pre-commit
          - script: |
              pip install tox  # Install Tox
              tox -e lint      # Run Tox with the linting environment
            displayName: "Running Tox Linting"
